name = "Yupiland"
author = "ScatherM02"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8f9069430b5dec98413fd06d967922cca5810dabea75e695a4adece0932f0bed"

[versions]
fabric = "0.19.3"
minecraft = "1.20.1"
