name = "Yupiland"
author = "ScatherM02"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0e2e11a2f883abd2d89c02eb31cd6940d4d3bafaf4f967433b9c52bb9e0aaf1d"

[versions]
fabric = "0.19.3"
minecraft = "1.20.1"
