name = "Yupiland"
author = "ScatherM02"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3047805490ee45a1cb464e671e9a6b1fa26b36d2f23c374ad517c02f2977fcff"

[versions]
fabric = "0.19.3"
minecraft = "1.20.1"
